FROM --platform=linux/$TARGETARCH golang:1.20 AS build

# Set destination for COPY
WORKDIR /build

# Download Go modules
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -o /bin/registryservice app/cmd/registryservice/*.go

FROM scratch

LABEL org.opencontainers.image.source=https://github.com/wgsaxton/ps_go_build_dist_apps

COPY --from=build /bin/registryservice /bin/registryservice

EXPOSE 3000

CMD ["/bin/registryservice"]