apiVersion: v1
kind: Service
metadata:
  
  name: gradingservice
  namespace: gradebookapp
  labels:
    app: gradebook
    service: grading
spec:
  type: ClusterIP
  selector:
    service: grading
  ports:
  - port: 6000
    targetPort: 6000