apiVersion: v1
kind: Service
metadata:
  name: teacherportalservice
  labels:
    app: gradebook
    service: teacherportal
spec:
  type: NodePort
  selector:
    service: teacherportal
  ports:
  - port: 5001
    targetPort: 5001