apiVersion: v1
kind: Service
metadata:
  
  name: logservice
  namespace: gradebookapp
  labels:
    app: gradebook
    service: log
spec:
  type: ClusterIP
  selector:
    service: log
  ports:
  - port: 4000
    targetPort: 4000