apiVersion: v1
kind: Service
metadata:
  name: registryservice
  labels:
    app: gradebook
    service: registry
spec:
  type: ClusterIP
  selector:
    service: registry
  ports:
  - port: 3000
    targetPort: 3000