apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-deployment
  namespace: gradebookapp
  labels:
    app: gradebook
    service: grading
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grading
  template:
    metadata:
      labels:
        service: grading
    spec:
      containers:
        - name: grading
          image: ghcr.io/wgsaxton/gradingservice:v0.04
          ports:
          - containerPort: 6000
          resources:
            limits:
              memory: "256M"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  
  name: gradingservice
  namespace: gradebookapp
  labels:
    app: gradebook
    service: grading
spec:
  type: ClusterIP
  selector:
    service: grading
  ports:
  - port: 6000
    targetPort: 6000